### PR TITLE
Fix addTour

### PR DESCRIPTION
**Pull request by VNTee**
Fix addTour/updateTour method
Fix integration addTour/updateTour tests

### CODE REVIEW

**Review by goponenkoev — APPROVED** [review]

**Review by Cisfinitum — APPROVED** [review]

**Review by goponenkoev — APPROVED** [review]

**Comment by ghost** [comment]
the problem is not fixed. Steps to reproduce the situation: try to call addTourMethod with object like this: 
toursOfferService.addTour(TourOffer.builder().build())
as a result we still have database exception, so we dont have any validation in the service, because the method call dao

**Review by ghost — CHANGES_REQUESTED** [review]
see a comment above

**Comment by ghost** [comment]
we want to use validations to add secure for income arguments for services, and there is no in common with annotations here. We just need to check properties and ensure, that we have valid values there
of course, we have ui validations for it, but we still can call this service method (it is public api) from other places in our code, and there is no validations here

**Comment by VNTee** [comment]
Done

**Review by ghost — APPROVED** [review]

**Review by MaltsevaKsenia — APPROVED** [review]

**Pull request merged**
